# Generated by Django 4.1.3 on 2022-12-07 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='day',
        ),
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
