# Generated by Django 4.1.3 on 2022-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_messages_media_messages_unsend_alter_messages_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reactions',
            field=models.IntegerField(default=0),
        ),
    ]
