# Generated by Django 4.1.3 on 2022-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_messages_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='reactions',
        ),
    ]
