# Generated by Django 4.1.3 on 2022-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_messages_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
